function o = ik_options()
% 与 C++ IKOptions 同名字段、单位和默认值；q_min/q_max 同时为空不限位。
o=struct('max_iterations',100,'position_tolerance',1e-6, ...
    'orientation_tolerance',1e-6,'lambda',1e-3,'max_joint_step',0.2, ...
    'rotation_weight',0.2,'svd_tolerance',1e-10,'sigma_threshold',0.05, ...
    'lambda_max',0.05,'max_backtracks',20,'q_min',[],'q_max',[]);
end
